### ISSUE TITLE
Cadastro de aluno

### ISSUE THREAD

**Issue by alexaugustobr** [alexaugustobr/ope-handcode#9]
- [ ] Cadastro de aluno
- [ ] Cadastro de aluno
- [ ] Cadastro de aluno
- [ ] Cadastro de aluno

https://app.leanboard.io/board/23da3d7b-8262-4d69-af40-1ef0f38b0d3d
